services:
  db:
    image: postgres:15
    container_name: foodtable_db
    environment:
      POSTGRES_DB: foodtable
      POSTGRES_USER: foodtable_user
      POSTGRES_PASSWORD: foodtable_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
