services:
  - type: web
    name: food-table
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: CLOUDFLARE_R2_BUCKET_NAME
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT_URL
        sync: false
      - key: CLOUDFLARE_R2_CUSTOM_DOMAIN
        sync: false
