# Generated by Django 5.2.7 on 2025-10-09 12:59

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encyclopedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_category', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('cultural_significance', models.TextField(blank=True)),
                ('popular_examples', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encyclopedia_entries', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.encyclopedia')),
                ('similar_dishes', models.ManyToManyField(blank=True, related_name='similar_to', to='content.encyclopedia')),
            ],
            options={
                'verbose_name_plural': 'Encyclopedia Entries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encyclopedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encyclopedia_tags', to='content.encyclopedia')),
            ],
            options={
                'verbose_name': 'Encyclopedia Tag',
                'verbose_name_plural': 'Encyclopedia Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddIndex(
            model_name='encyclopedia',
            index=models.Index(fields=['slug'], name='content_enc_slug_660e52_idx'),
        ),
        migrations.AddIndex(
            model_name='encyclopedia',
            index=models.Index(fields=['parent'], name='content_enc_parent__dd3d89_idx'),
        ),
        migrations.AddIndex(
            model_name='encyclopedia',
            index=models.Index(fields=['cuisine_type'], name='content_enc_cuisine_f555e0_idx'),
        ),
        migrations.AddIndex(
            model_name='encyclopedia',
            index=models.Index(fields=['dish_category'], name='content_enc_dish_ca_f46924_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='encyclopediatag',
            unique_together={('encyclopedia', 'tag')},
        ),
    ]
