# Generated by Django 5.2.7 on 2025-10-11 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_recipe_recipetag_recipe_content_rec_slug_632a87_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_category', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encyclopedia_version_changes', to=settings.AUTH_USER_MODEL)),
                ('encyclopedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.encyclopedia')),
            ],
            options={
                'verbose_name': 'Encyclopedia Version',
                'verbose_name_plural': 'Encyclopedia Versions',
                'ordering': ['-version'],
                'unique_together': {('encyclopedia', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(max_length=10)),
                ('ingredients_snapshot', models.JSONField(blank=True, default=list)),
                ('steps_snapshot', models.JSONField(blank=True, default=list)),
                ('tips', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_version_changes', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Version',
                'verbose_name_plural': 'Recipe Versions',
                'ordering': ['-version'],
                'unique_together': {('recipe', 'version')},
            },
        ),
    ]
