# Generated by Django 5.2.7 on 2025-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_add_search_vector_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='encyclopedia',
            name='encyclopedia_search_vector_gin_idx',
        ),
        migrations.AddField(
            model_name='reviewdish',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for this specific dish'),
        ),
    ]
