# Generated by Django 5.2.7 on 2025-10-16 03:45

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def populate_recipe_search_vector(apps, schema_editor):
    """
    Populate search_vector field for all existing Recipe entries.
    """
    Recipe = apps.get_model('content', 'Recipe')

    # Update all recipes with search vector
    for recipe in Recipe.objects.all():
        Recipe.objects.filter(pk=recipe.pk).update(
            search_vector=SearchVector('name', weight='A') + SearchVector('description', weight='B')
        )


def populate_review_search_vector(apps, schema_editor):
    """
    Populate search_vector field for all existing Review entries.
    """
    Review = apps.get_model('content', 'Review')

    # Update all reviews with search vector
    for review in Review.objects.all():
        search_vector_expr = SearchVector('restaurant_name', weight='A')

        # Add title if it exists
        if review.title:
            search_vector_expr = search_vector_expr + SearchVector('title', weight='B')

        # Add notes if they exist
        if review.notes:
            search_vector_expr = search_vector_expr + SearchVector('notes', weight='C')

        Review.objects.filter(pk=review.pk).update(search_vector=search_vector_expr)


def reverse_populate_search_vector(apps, schema_editor):
    """
    Clear search_vector fields (reverse operation).
    """
    Recipe = apps.get_model('content', 'Recipe')
    Review = apps.get_model('content', 'Review')

    Recipe.objects.all().update(search_vector=None)
    Review.objects.all().update(search_vector=None)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_encyclopedia_encyclopedia_search_vector_gin_idx_and_more'),
    ]

    operations = [
        # Add GIN index on Recipe search_vector field for fast full-text search
        migrations.AddIndex(
            model_name='recipe',
            index=GinIndex(fields=['search_vector'], name='recipe_search_vector_gin_idx'),
        ),
        # Add GIN index on Review search_vector field for fast full-text search
        migrations.AddIndex(
            model_name='review',
            index=GinIndex(fields=['search_vector'], name='review_search_vector_gin_idx'),
        ),
        # Populate search_vector for all existing recipes
        migrations.RunPython(populate_recipe_search_vector, reverse_populate_search_vector),
        # Populate search_vector for all existing reviews
        migrations.RunPython(populate_review_search_vector, reverse_populate_search_vector),
    ]
