# Generated by Django 5.2.7 on 2025-10-23 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_populate_recipe_review_search_vectors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewdish',
            options={'ordering': ['review', 'id'], 'verbose_name': 'Review Dish', 'verbose_name_plural': 'Review Dishes'},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipe_search_vector_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_search_vector_gin_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reviewdish',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reviewdish',
            name='encyclopedia_entry',
            field=models.ForeignKey(blank=True, help_text='Optional link to encyclopedia entry (can be set manually after import)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_reviews', to='content.encyclopedia'),
        ),
    ]
