# Generated by Django 5.2.7 on 2025-10-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_make_reviewdish_encyclopedia_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdish',
            name='dish_name',
            field=models.CharField(blank=True, help_text='Dish name as parsed from import (used when encyclopedia_entry is not linked)', max_length=255),
        ),
    ]
