# Generated by Django 5.2.7 on 2025-11-08 23:30

from django.db import migrations, models


def make_similar_dishes_bidirectional(apps, schema_editor):
    """
    Data migration to add reverse relationships for existing similar dish links.
    When changing from symmetrical=False to symmetrical=True, we need to ensure
    that all existing one-way relationships become bidirectional.
    """
    Encyclopedia = apps.get_model('content', 'Encyclopedia')

    # Get all encyclopedia entries that have similar dishes
    entries_with_similar = Encyclopedia.objects.prefetch_related('similar_dishes').all()

    for entry in entries_with_similar:
        # Get all similar dishes for this entry
        similar_dish_ids = list(entry.similar_dishes.values_list('id', flat=True))

        # For each similar dish, add the reverse relationship
        for similar_id in similar_dish_ids:
            try:
                similar_entry = Encyclopedia.objects.get(id=similar_id)
                # Add reverse relationship (this will be idempotent - won't create duplicates)
                similar_entry.similar_dishes.add(entry)
            except Encyclopedia.DoesNotExist:
                # Skip if the related entry doesn't exist (shouldn't happen but being safe)
                pass


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - remove the bidirectional relationships.
    This is a no-op as we can't reliably restore the original one-way state.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_reviewdish_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encyclopedia',
            name='similar_dishes',
            field=models.ManyToManyField(blank=True, to='content.encyclopedia'),
        ),
        migrations.RunPython(make_similar_dishes_bidirectional, reverse_migration),
    ]
