# Generated by Django 5.2.7 on 2025-11-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_make_similar_dishes_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='encyclopedia',
            name='is_placeholder',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='encyclopedia',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
