# Generated by Django 5.2.7 on 2025-11-11 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_encyclopedia_is_placeholder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(default='basic-info', help_text='Current step ID in the review modal', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='All form data including basic info, location, rating, and dishes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this draft', on_delete=django.db.models.deletion.CASCADE, related_name='review_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Draft',
                'verbose_name_plural': 'Review Drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='content_rev_user_id_620c2c_idx')],
            },
        ),
    ]
