# Generated by Django 5.2.7 on 2026-05-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_remove_restaurant_old_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RestaurantDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('had', 'Had'), ('wishlist', 'Wishlist')], default='wishlist', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('friend', 'Friend'), ('article', 'Article'), ('social', 'Social Media'), ('word_of_mouth', 'Word of Mouth'), ('other', 'Other')], max_length=20)),
                ('source_detail', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encyclopedia_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_dishes', to='content.encyclopedia')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='content.restaurant')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_dish_entries', to='content.review')),
            ],
            options={
                'ordering': ['dish_name'],
            },
        ),
    ]
