# Generated by Django 5.2.7 on 2026-05-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_restaurant_visited_and_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdish',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
