# Generated by Django 5.2.7 on 2026-06-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_delete_wishlistinboxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
