# Generated by Django 5.2.7 on 2026-06-20 05:20

import django.contrib.postgres.search
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def populate_restaurant_search_vector(apps, schema_editor):
    """
    Populate search_vector field for all existing Restaurant entries.
    """
    Restaurant = apps.get_model('content', 'Restaurant')

    for restaurant in Restaurant.objects.all():
        Restaurant.objects.filter(pk=restaurant.pk).update(
            search_vector=(
                SearchVector('name', weight='A')
                + SearchVector('city', weight='B')
                + SearchVector('street_address', weight='B')
                + SearchVector('province', weight='C')
                + SearchVector('country', weight='C')
            )
        )


def reverse_populate_search_vector(apps, schema_editor):
    """
    Clear search_vector field (reverse operation).
    """
    Restaurant = apps.get_model('content', 'Restaurant')
    Restaurant.objects.all().update(search_vector=None)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_restaurant_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        # Add GIN index on search_vector field for fast full-text search
        migrations.AddIndex(
            model_name='restaurant',
            index=GinIndex(fields=['search_vector'], name='restaurant_search_vector_gin_idx'),
        ),
        # Populate search_vector for all existing restaurants
        migrations.RunPython(populate_restaurant_search_vector, reverse_populate_search_vector),
    ]
