# Generated by Django 5.2.7 on 2026-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_restaurant_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_pop_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
